### ISSUE TITLE
Lyrics support

### ISSUE THREAD

**Issue by grinceur** [Crerader/KnapCheese#2]
### Expected behavior

Be able to use a command to print the lyrics of the currently playing song.
Maybe also a specified song.

### Exemple usage

`;;lyrics`

`;;ly couic couic soviet suprem`

**Comment by Jjmarco** [comment]
Done! Usage:
`;;lyrics`: show the lyrics of the song currently playing if there is one
`;;lyrics <song name>`: show the lyrics of the given song
`;;lyrics @<member>`: show the lyrics of the song that `<member>` is listening to on Spotify (member must have linked their Spotify account, allowed sharing of the listening status and actually be listening to something)
